import { ChatMessage, Conversation, SafeUser } from "@/types";
import { initialMockUsers, mockCurrentUser } from "./users";
import { initialMockListings } from "./listings";

const userSophia = initialMockUsers.find((u) => u.id === "user-2") || initialMockUsers[1];
const userMatteo = initialMockUsers.find((u) => u.id === "user-3") || initialMockUsers[2];
const userFatima = initialMockUsers.find((u) => u.id === "user-4") || initialMockUsers[3];
const userYuki = initialMockUsers.find((u) => u.id === "user-5") || initialMockUsers[4];
const userLiam = initialMockUsers.find((u) => u.id === "user-6") || initialMockUsers[5];
const userElena = initialMockUsers.find((u) => u.id === "user-7") || initialMockUsers[6];
const userEmma = initialMockUsers.find((u) => u.id === "user-8") || initialMockUsers[7];

export const userSupport: SafeUser = {
  id: "user-support",
  name: "DARNA Support",
  email: "support@darna.com",
  emailVerified: "2022-01-01T00:00:00.000Z",
  image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=400&q=80",
  createdAt: "2022-01-01T00:00:00.000Z",
  updatedAt: "2024-01-01T00:00:00.000Z",
  favoriteIds: [],
  role: "admin",
  location: "San Francisco, CA",
};

export const initialMockMessages: ChatMessage[] = [
  // Conversation 1 (Sophia Laurent - Issy-les-Moulineaux) - 16 messages for full thread scrolling
  {
    id: "msg-101",
    conversationId: "conv-1",
    senderId: "user-2",
    receiverId: "user-1",
    content: "Hello Alex! Thank you for booking our apartment in Issy-les-Moulineaux. Let me know if you have any questions about checking in!",
    createdAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    isRead: true,
  },
  {
    id: "msg-102",
    conversationId: "conv-1",
    senderId: "user-1",
    receiverId: "user-2",
    content: "Hi Sophia! We're super excited. Is it possible to check in around 2 PM?",
    createdAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    isRead: true,
  },
  {
    id: "msg-103",
    conversationId: "conv-1",
    senderId: "user-2",
    receiverId: "user-1",
    content: "Yes absolutely, 2 PM works great. I will send you the door code and building access details in the morning.",
    createdAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    isRead: true,
  },
  {
    id: "msg-104",
    conversationId: "conv-1",
    senderId: "user-1",
    receiverId: "user-2",
    content: "Awesome, thanks Sophia! Also, does the building have an elevator? We will have two medium suitcases with us.",
    createdAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    isRead: true,
  },
  {
    id: "msg-105",
    conversationId: "conv-1",
    senderId: "user-2",
    receiverId: "user-1",
    content: "Yes, there is an elevator located right past the main courtyard on your right. It fits up to 4 people comfortably.",
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    isRead: true,
  },
  {
    id: "msg-106",
    conversationId: "conv-1",
    senderId: "user-1",
    receiverId: "user-2",
    content: "That's a relief! And what's the best way to get to your place from Charles de Gaulle airport?",
    createdAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    isRead: true,
  },
  {
    id: "msg-107",
    conversationId: "conv-1",
    senderId: "user-2",
    receiverId: "user-1",
    content: "Taking RER B to Saint-Michel Notre-Dame, then transferring to Metro Line 12 straight to Corentin Celton is the fastest route (about 45 mins total).",
    createdAt: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
    isRead: true,
  },
  {
    id: "msg-108",
    conversationId: "conv-1",
    senderId: "user-1",
    receiverId: "user-2",
    content: "Super clear! What is the Wi-Fi network and password once we get into the apartment?",
    createdAt: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    isRead: true,
  },
  {
    id: "msg-109",
    conversationId: "conv-1",
    senderId: "user-2",
    receiverId: "user-1",
    content: "The network is 'ParisianNest_5G' and the password is 'WelcomeToParis2026!'. You can also scan the QR code sticker on the fridge.",
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    isRead: true,
  },
  {
    id: "msg-110",
    conversationId: "conv-1",
    senderId: "user-1",
    receiverId: "user-2",
    content: "Great! Are there any good bakeries or coffee spots nearby that you personally recommend?",
    createdAt: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
    isRead: true,
  },
  {
    id: "msg-111",
    conversationId: "conv-1",
    senderId: "user-2",
    receiverId: "user-1",
    content: "Oh absolutely! 'Boulangerie Pichard' right on Rue de Vaugirard has award-winning croissants and baguettes. Open at 7 AM!",
    createdAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    isRead: true,
  },
  {
    id: "msg-112",
    conversationId: "conv-1",
    senderId: "user-1",
    receiverId: "user-2",
    content: "Sounds delicious! We will definitely stop by there on our first morning.",
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    isRead: true,
  },
  {
    id: "msg-113",
    conversationId: "conv-1",
    senderId: "user-2",
    receiverId: "user-1",
    content: "Let me know once you arrive and have settled in. I'm always available if you need any extra towels or restaurant bookings!",
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    isRead: true,
  },
  {
    id: "msg-114",
    conversationId: "conv-1",
    senderId: "user-1",
    receiverId: "user-2",
    content: "Will do! Our flight just touched down, heading through customs now.",
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    isRead: true,
  },
  {
    id: "msg-115",
    conversationId: "conv-1",
    senderId: "user-2",
    receiverId: "user-1",
    content: "Welcome to Paris! The keys are waiting in the lockbox (code: 4829). Safe travels on the metro!",
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    isRead: false,
  },

  // Conversation 2 (Matteo Rossi - Room in Paris)
  {
    id: "msg-201",
    conversationId: "conv-2",
    senderId: "user-1",
    receiverId: "user-3",
    content: "Hi Matteo, what is the closest metro station to your place?",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    isRead: true,
  },
  {
    id: "msg-202",
    conversationId: "conv-2",
    senderId: "user-3",
    receiverId: "user-1",
    content: "Ciao Alex! Station Saint-Germain-des-Prés is only a 3-minute walk. Very convenient and safe!",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    isRead: true,
  },
  {
    id: "msg-203",
    conversationId: "conv-2",
    senderId: "user-1",
    receiverId: "user-3",
    content: "Perfect, thanks so much! See you next week.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    isRead: true,
  },

  // Conversation 3 (Fatima Al-Mansoor - Hosting inquiry)
  {
    id: "msg-301",
    conversationId: "conv-3",
    senderId: "user-4",
    receiverId: "user-1",
    content: "Hi Alex! I love your space. Do you have high-speed Wi-Fi suitable for Zoom video calls?",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    isRead: true,
  },
  {
    id: "msg-302",
    conversationId: "conv-3",
    senderId: "user-1",
    receiverId: "user-4",
    content: "Hi Fatima! Yes, we have dedicated fiber optic internet (300 Mbps download and upload).",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(),
    isRead: true,
  },
  {
    id: "msg-303",
    conversationId: "conv-3",
    senderId: "user-4",
    receiverId: "user-1",
    content: "That sounds wonderful! I will confirm my dates by tomorrow evening.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    isRead: true,
  },

  // Conversation 4 (DARNA Support)
  {
    id: "msg-401",
    conversationId: "conv-4",
    senderId: "user-support",
    receiverId: "user-1",
    content: "Welcome to DARNA Support. Your official reservation invoice has been sent to your email.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    isRead: true,
  },
  {
    id: "msg-402",
    conversationId: "conv-4",
    senderId: "user-1",
    receiverId: "user-support",
    content: "Thank you for the quick help!",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 70).toISOString(),
    isRead: true,
  },
  {
    id: "msg-403",
    conversationId: "conv-4",
    senderId: "user-support",
    receiverId: "user-1",
    content: "You're very welcome! If there's anything else you need, our team is available 24/7.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 68).toISOString(),
    isRead: true,
  },

  // Conversation 5 (Liam O'Connor)
  {
    id: "msg-501",
    conversationId: "conv-5",
    senderId: "user-6",
    receiverId: "user-1",
    content: "Hi Alex, hope you're having a great week! Looking forward to your visit to Dublin.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 80).toISOString(),
    isRead: true,
  },

  // Conversation 6 (Elena Rostova)
  {
    id: "msg-601",
    conversationId: "conv-6",
    senderId: "user-7",
    receiverId: "user-1",
    content: "Grüezi Alex! The ski conditions in Zermatt are incredible this month. Fireplace is all prepped for you!",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    isRead: true,
  },

  // Conversation 7 (Emma Watson)
  {
    id: "msg-701",
    conversationId: "conv-7",
    senderId: "user-8",
    receiverId: "user-1",
    content: "Hi Alex! Thanks for accepting the booking request. Can we request an early bag drop off?",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 110).toISOString(),
    isRead: true,
  },

  // Conversation 8 (Yuki Tanaka)
  {
    id: "msg-801",
    conversationId: "conv-8",
    senderId: "user-5",
    receiverId: "user-1",
    content: "Konnichiwa Alex! Tea ceremony reservation is confirmed for Friday at 4 PM.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 130).toISOString(),
    isRead: true,
  },
];

export const initialMockConversations: Conversation[] = [
  {
    id: "conv-1",
    participantIds: ["user-1", "user-2"],
    participants: [mockCurrentUser, userSophia],
    listingId: "paris-1",
    listing: initialMockListings.find((l) => l.id === "paris-1") || initialMockListings[0],
    reservationDetails: {
      startDate: "2026-11-27",
      endDate: "2026-11-29",
      status: "Confirmed",
      guestCount: 2,
    },
    category: "guests",
    lastMessage: initialMockMessages[14],
    lastMessageAt: initialMockMessages[14].createdAt,
    unreadCount: 1,
  },
  {
    id: "conv-2",
    participantIds: ["user-1", "user-3"],
    participants: [mockCurrentUser, userMatteo],
    listingId: "paris-2",
    listing: initialMockListings.find((l) => l.id === "paris-2") || initialMockListings[1],
    reservationDetails: {
      startDate: "2026-12-15",
      endDate: "2026-12-18",
      status: "Confirmed",
      guestCount: 1,
    },
    category: "guests",
    lastMessage: initialMockMessages[17],
    lastMessageAt: initialMockMessages[17].createdAt,
    unreadCount: 0,
  },
  {
    id: "conv-3",
    participantIds: ["user-1", "user-4"],
    participants: [mockCurrentUser, userFatima],
    listingId: "paris-3",
    listing: initialMockListings.find((l) => l.id === "paris-3") || initialMockListings[2],
    reservationDetails: {
      startDate: "2027-01-10",
      endDate: "2027-01-14",
      status: "Inquiry",
      guestCount: 2,
    },
    category: "hosting",
    lastMessage: initialMockMessages[20],
    lastMessageAt: initialMockMessages[20].createdAt,
    unreadCount: 0,
  },
  {
    id: "conv-4",
    participantIds: ["user-1", "user-support"],
    participants: [mockCurrentUser, userSupport],
    category: "support",
    lastMessage: initialMockMessages[23],
    lastMessageAt: initialMockMessages[23].createdAt,
    unreadCount: 0,
  },
  {
    id: "conv-5",
    participantIds: ["user-1", "user-6"],
    participants: [mockCurrentUser, userLiam],
    listingId: "paris-4",
    listing: initialMockListings.find((l) => l.id === "paris-4") || initialMockListings[3],
    reservationDetails: {
      startDate: "2027-02-05",
      endDate: "2027-02-10",
      status: "Confirmed",
      guestCount: 2,
    },
    category: "guests",
    lastMessage: initialMockMessages[24],
    lastMessageAt: initialMockMessages[24].createdAt,
    unreadCount: 0,
  },
  {
    id: "conv-6",
    participantIds: ["user-1", "user-7"],
    participants: [mockCurrentUser, userElena],
    listingId: "paris-5",
    listing: initialMockListings.find((l) => l.id === "paris-5") || initialMockListings[0],
    reservationDetails: {
      startDate: "2027-03-01",
      endDate: "2027-03-06",
      status: "Confirmed",
      guestCount: 4,
    },
    category: "guests",
    lastMessage: initialMockMessages[25],
    lastMessageAt: initialMockMessages[25].createdAt,
    unreadCount: 0,
  },
  {
    id: "conv-7",
    participantIds: ["user-1", "user-8"],
    participants: [mockCurrentUser, userEmma],
    listingId: "paris-2",
    listing: initialMockListings.find((l) => l.id === "paris-2") || initialMockListings[1],
    category: "hosting",
    lastMessage: initialMockMessages[26],
    lastMessageAt: initialMockMessages[26].createdAt,
    unreadCount: 0,
  },
  {
    id: "conv-8",
    participantIds: ["user-1", "user-5"],
    participants: [mockCurrentUser, userYuki],
    listingId: "paris-3",
    listing: initialMockListings.find((l) => l.id === "paris-3") || initialMockListings[2],
    category: "guests",
    lastMessage: initialMockMessages[27],
    lastMessageAt: initialMockMessages[27].createdAt,
    unreadCount: 0,
  },
];
